package com.twjoin.arvin.chocolabs_exam.db;

import com.twjoin.arvin.chocolabs_exam.db.model.DramaEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dramaEntityDaoConfig;

    private final DramaEntityDao dramaEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dramaEntityDaoConfig = daoConfigMap.get(DramaEntityDao.class).clone();
        dramaEntityDaoConfig.initIdentityScope(type);

        dramaEntityDao = new DramaEntityDao(dramaEntityDaoConfig, this);

        registerDao(DramaEntity.class, dramaEntityDao);
    }
    
    public void clear() {
        dramaEntityDaoConfig.clearIdentityScope();
    }

    public DramaEntityDao getDramaEntityDao() {
        return dramaEntityDao;
    }

}
